campaigns/urls.py
from django.urls import path 
from campaigns.views.campaign import (campaigns, campaign_details, 
                                      create_campaign, update_campaign, delete_campaign, manage_campaigns, manage_campaign, generate_contributors_list)
from campaigns.views.contribution import (
    create_contribution, cancel_contribution, contribution, contributions, manage_contribution, manage_contributions
)
from campaigns.views.campaign_update import create_campaign_update, delete_campaign_update

app_name = "campaigns"
urlpatterns = [
    path("", campaigns, name="campaigns"),
    path("campaign/manage", manage_campaigns, name="manage-campaigns"),
    path("campaign/create", create_campaign, name="create-campaign"),
    path("<slug:category_slug>", campaigns, name="campaign-by-category"),
    path("campaing/<slug:campaign_slug>", campaign_details, name="campaign"),
    path("campaign/manage/<uuid:campaign_id>", manage_campaign, name="manage-campaign"),
    path("campaign/update/<slug:campaign_slug>", update_campaign, name="update-campaign"),
    path("campaign/delete/<slug:campaign_slug>", delete_campaign, name="delete-campaign"),

    path("campaign/updates/create/<slug:campaign_slug>", create_campaign_update, name="create-campaign-update"),
    path("campaign/updates/delete/<uuid:update_id>", delete_campaign_update, name="delete-campaign-update"),

    path("contributions/all", contributions, name="all-contributions"),
    path("contribution/all/<uuid:campaign_id>", contributions, name="contributions"),
    path("contribution/manage", manage_contributions, name="manage-contributions"),
    path("contribution/<uuid:campaign_id>/<uuid:contribution_id>", contribution, name="contribution"),
    path("contribution/manage/<uuid:contribution_id>", manage_contribution, name="manage-contribution"),
    path("contribution/create/<uuid:campaign_id>", create_contribution, name="create-contribution"),
    path("contribution/cancel/<uuid:contribution_id>", cancel_contribution, name="cancel-contribution"),
    path("contribution/generate/contributors/<uuid:campaign_id>", generate_contributors_list, name="generate-contributors-list")
    
]

home/urls.py
from django.urls import path
from home.views import home, search, news, post_details, help, contact, terms_and_conditions

app_name = "home"
urlpatterns = [
    path("", home, name="home"),
    path("privacy", terms_and_conditions, name="terms"),
    path("privacy/<slug:terms_slug>", terms_and_conditions, name="privacy"),
    path("faq", help, name="help"),
    path("contact", contact, name="contact"),
    path("search", search, name="search"),
    path("posts", news, name="news"),
    path("posts/<slug:category_slug>", news, name="news-category"),
    path("posts/<slug:category_slug>/<slug:post_slug>", post_details, name="news-details")
]

ndwandwafam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("campaigns/", include("campaigns.urls", namespace="campaigns")),
    path("events/", include("events.urls", namespace="events")),
    path("payments/", include("payments.urls", namespace="payments")),
    path("company/", include("company.urls", namespace="company")),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campaigns/models.py
import uuid
from datetime import timedelta
import decimal
from django.urls import reverse
from django.core.validators import MinValueValidator
from accounts.models import AbstractCreate
from campaigns.utils import handle_campaign_file_upload, PaymentStatus, Tip
from campaigns.utils import generate_slug
from accounts.utils import StatusChoices
from django.db import models
from django.utils import timezone
from home.models import CategoryModel
from django.dispatch import receiver
from django.db.models.signals import pre_delete
from django.utils.safestring import mark_safe
from django.utils.translation import gettext as _
from taggit.managers import TaggableManager
from django.contrib.auth import get_user_model
from tinymce.models import HTMLField

User = get_user_model()

def in_fourteen_days():
    return timezone.now() + timedelta(days=14)

def five_days():
    return timezone.now() + timedelta(days=5)

class AbstractPayment(models.Model):
    payment_method_type = models.CharField(max_length=50, null=True, blank=True)
    payment_method_card_holder = models.CharField(max_length=50, null=True, blank=True)
    payment_method_masked_card = models.CharField(max_length=50, null=True, blank=True)
    payment_method_scheme = models.CharField(max_length=50, null=True, blank=True)
    payment_date = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        abstract = True

class CampaignModel(AbstractCreate):
    image = models.ImageField(help_text=_("Upload campaign image."), upload_to=handle_campaign_file_upload, blank=True, null=True)
    title = models.CharField(help_text=_("Enter title for your campaign"), max_length=150)
    slug = models.SlugField(max_length=250, blank=True)
    organiser = models.ForeignKey(User, on_delete=models.CASCADE, default=None, related_name="campaigns")
    category = models.ForeignKey(CategoryModel, on_delete=models.PROTECT, related_name="campaigns")
    details = HTMLField(help_text=_("Enter additional details about your campaign"))
    target = models.DecimalField(help_text=_("Enter target amount"),max_digits=1000, decimal_places=2, default=0.00)
    current_amount = models.DecimalField(max_digits=1000, decimal_places=2, default=0.00)
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(default=in_fourteen_days, validators=[MinValueValidator(timezone.now(), "Date should not be less that today's date")])
    status = models.CharField(max_length=50, choices=StatusChoices.choices, default=StatusChoices.NOT_APPROVED)
    is_featured = models.BooleanField(default=False)
    tags = TaggableManager(blank=True)

    class Meta:
        verbose_name = _("Campaigns")
        verbose_name_plural = _("Campaigns")
        ordering = ["-created"]

    def get_absolute_url(self):
        return reverse("campaigns:campaign", kwargs={"campaign_slug": self.slug})

    def get_days(self):
        date = self.end_date - timezone.now()
        if date.days < 0:
            return "0 days"
        if date.days > 1:
            return f"{date.days} days"
        else:
            return f"{date.days} day"

    def get_percentage_of_donated_fund(self):
        val = self.current_amount / self.target
        perc = val * 100
        if perc > decimal.Decimal(100):
            return round(100, 2)
        return round(perc, 2)
    

    def __str__(self):
        return str(self.title)
    
    def image_tag(self):
        if self.image.url is not None:
            return mark_safe(f"<img src={self.image.url} alt={self.title}-image height='60' width='90' />")
        return ""
    
    def thumpnail(self):
        if self.image.url is not None:
            return mark_safe(f"<img src={self.image.url} alt={self.organiser.first_name}-image height='60' width='60' style='border-radius: 50%; height: 40px; width: 40px;' />")
        return ""

    def content_safe(self):
        return mark_safe(self.details)


class CampaignUpdateModel(AbstractCreate):
    campaign = models.ForeignKey(CampaignModel, on_delete=models.CASCADE, related_name="updates")
    title = models.CharField(max_length=250)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Campaign Update'
        verbose_name_plural = 'Campaign Updates'

    def __str__(self) -> str:
        return f'Update for {self.campaign.title} - {self.created}'
    
class ContributionModel(AbstractCreate, AbstractPayment):
    order_number = models.CharField(max_length=300, editable=False, unique=True)
    checkout_id = models.CharField(max_length=200, unique=True, null=True, blank=True, db_index=True)
    amount = models.DecimalField(max_digits=1000, decimal_places=2, help_text=_("Enter contribution amount"))
    tip = models.CharField(default=Tip.TEN, max_length=25, choices=Tip.choices)
    total_amount = models.DecimalField(max_digits=1000, decimal_places=2)
    accepted_laws = models.BooleanField(default=True)
    message = models.TextField(blank=True, null=True)
    paid = models.CharField(max_length=40, choices=PaymentStatus.choices, default=PaymentStatus.NOT_PAID)
    campaign = models.ForeignKey(CampaignModel, on_delete=models.CASCADE, related_name="contributions")
    anonymous = models.BooleanField(default=False)
    contributor = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=None, null=True, related_name="contributions")
    receipt = models.FileField(null=True, upload_to="contributions/receipts/")

    class Meta:
        verbose_name = _("Contribution")
        verbose_name_plural = _("Contributions")
        ordering = ["-created"]

    def calculate_tip_amount(self):
        if self.tip == "10%":
            tip_amount = decimal.Decimal(self.amount) * decimal.Decimal((10 / 100))
        elif self.tip == "15%":
            tip_amount = decimal.Decimal(self.amount) * decimal.Decimal((15 / 100))
        elif self.tip == "20%":
            tip_amount = decimal.Decimal(self.amount) * decimal.Decimal((20 / 100))
        else:
            tip_amount = decimal.Decimal(self.amount) * decimal.Decimal((25 / 100))
        return round(tip_amount, 2)

    def calculate_total(self):
        
        return decimal.Decimal(self.amount) + self.calculate_tip_amount()
    
    

    def __str__(self):
        return str(self.amount)
    
    def contribution_percentage(self):
        perc = (self.amount / self.campaign.target) * 100
        return f"{round(perc, 2)}%"
    
    def get_absolute_url(self):
        return reverse("campaigns:contribution", kwargs={"campaign_id": self.campaign.id, "contribution_id": self.id})
    

    def save(self, *args, **kwargs):
        self.total_amount = round(self.calculate_total(), 2)
        super(ContributionModel, self).save(*args, **kwargs)

@receiver(pre_delete, sender=CampaignModel)
def delete_campaign_image_hook(sender, instance, using, **kwargs):
    instance.image.delete()

@receiver(pre_delete, sender=ContributionModel)
def delete_campaign_image_hook(sender, instance, using, **kwargs):
    instance.receipt.delete()

campaigns/views/campaign_update.py
from campaigns.models import CampaignModel, CampaignUpdateModel
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from campaigns.forms import CampaignUpdateForm
from campaigns.tasks import update_contributors
from django.contrib.sites.shortcuts import get_current_site


@login_required
def create_campaign_update(request, campaign_slug):
    campaign = get_object_or_404(CampaignModel, slug=campaign_slug, organiser = request.user)
    if request.method == 'POST':
        form = CampaignUpdateForm(request.POST)
        if form.is_valid():
            update = form.save(commit=False)
            update.campaign = campaign
            update.save()
            messages.success(request, "Campaign update was successfully added")
            protocol = "https" if request.is_secure() else "http"
            domain = get_current_site(request).domain
            update_contributors.delay(update.id, domain, protocol)
            return redirect("campaigns:manage-campaign", campaign_id=campaign.id)
        else:
            messages.error(request, "Something went wrong, please fix errors below")
            return render(request, "campaigns/updates/create.html", {"form": form})
    
    return render(request, "campaigns/updates/create.html", {"form": CampaignUpdateForm()})

@login_required
def delete_campaign_update(request, update_id):
    campaign_update = get_object_or_404(CampaignUpdateModel, id = update_id)
    
    if request.method == "POST":
        campaign_update.delete()
        messages.success(request, "Campaign Update Deleted successfully!")
        return redirect("campaigns:manage-campaign", campaign_id=campaign_update.campaign.id)
    
    return render(request, "campaigns/delete/confirm_delete.html", {"message": f"Are you sure you want to delete this campaign update ({campaign_update.title})?", "title": "Delete campaign update"})

campaigns/views/contribution.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from campaigns.models import CampaignModel, ContributionModel
from campaigns.utils import generate_order_number, PaymentStatus
from accounts.utils import StatusChoices
from campaigns.forms import ContributionForm
from django.contrib import messages
from django.utils import timezone

@login_required
def manage_contributions(request):
    contributions = ContributionModel.objects.filter(contributor = request.user).select_related("campaign", "contributor")
    return render(request, "campaigns/contributions/manage/contributions.html", {"contributions": contributions})

@login_required
def manage_contribution(request, contribution_id):
    contributions = ContributionModel.objects.filter(contributor = request.user).select_related("campaign", "contributor")
    contribution = get_object_or_404(contributions, id=contribution_id)

    return render(request, "campaigns/contributions/manage/contribution.html", {"order": contribution})

@login_required
def contributions(request, campaign_id = None):
    
    contributions = None
    campaign_model = None

    if campaign_id:
        campaign_model = get_object_or_404(CampaignModel, id=campaign_id, organiser=request.user)
        contributions = ContributionModel.objects.filter(campaign = campaign_model).select_related("contributor")
    else:
        campaigns = CampaignModel.objects.prefetch_related("contributions").filter(organiser=request.user).order_by("-created")
        
        contributions = []
        for campaign in campaigns:
            contributions.extend(campaign.contributions.all())
        

    return render(request, "campaigns/contributions/contributions.html", {"orders": contributions, "campaign": campaign_model})

@login_required
def contribution(request, contribution_id, campaign_id):
    campaign = get_object_or_404(CampaignModel, id=campaign_id, organiser=request.user)
    contributions = ContributionModel.objects.filter(campaign = campaign).select_related("contributor")
    contribution = get_object_or_404(contributions, id=contribution_id)
    return render(request, "campaigns/contributions/contribution.html", {"order": contribution})

@login_required
def create_contribution(request, campaign_id):
    campaign = get_object_or_404(CampaignModel.objects.filter(status = StatusChoices.APPROVED), id = campaign_id)
    date = campaign.end_date  - timezone.now()
    if date.days <= 0:
        messages.error(request, "Sorry, this campaign is closed and no longer receives contributions, Thank you")
        campaign.status = StatusChoices.COMPLETED
        campaign.save(update_fields=["status"])
        return redirect("campaigns:campaign", campaign_slug=campaign.slug)
    
    if request.method == 'POST':
        form = ContributionForm(request.POST)
        if form.is_valid():
            contribution = form.save(commit=False)
            contribution.accepted_laws = True
            contribution.campaign = campaign
            contribution.contributor = request.user
            contribution.order_number = generate_order_number(ContributionModel)
            contribution.save()
            messages.success(request, "Your contribution was added successfully")
            return redirect("payments:contribution-payment", contribution_id=contribution.id)
        else:
           messages.error(request, "Please fix errors below")
           return render(request, "campaigns/contributions/summary.html", {"campaign": campaign, "form": form}) 

    form = ContributionForm()
    return render(request, "campaigns/contributions/summary.html", {"campaign": campaign, "form": form})

@login_required
def cancel_contribution(request, contribution_id):
    contribution = get_object_or_404(ContributionModel, contributor = request.user, id = contribution_id)
    campaign_id = contribution.campaign.id
    if contribution.paid == PaymentStatus.PAID:
        messages.warning(request, "You cannot cancel an already paid or pending payment contribution, please visit our <a href='' class='text-custom-primary'>refund policy</a>")
        return redirect("campaigns:contributions", campaign_id=campaign_id)
    
    if request.method == "POST":
        contribution.delete()
        return redirect("campaigns:contributions", campaign_id=campaign_id)
    
    return render(request, "campaigns/delete/confirm_delete.html", {"message": f"Are you sure you want to cancel this contribution ({contribution.order_number})?", "title": "Cancel Contribution"})

campaigns/templates/campaigns/campaign/create.html
{% extends '_manage.html' %}
{% load static %}

{% block title %}Create campaign{% endblock title %}

{% block content %}

<div class="w-full pb-20 h-full bg-white">
    <div class="space-y-4 bg-white w-full relative">
        {% include "includes/errors.html" %}
        <div class="px-4">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="flex items-start flex-col gap-7">
                    <div class="bg-white w-full">
                        <h6 class="text-custom-h text-base mt-3 mb-6 font-bold uppercase">
                            Campaign Information
                        </h6>
                        <div class="flex flex-wrap">
                            <div class="w-full lg:w-12/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label for="id_image">
                                        campaign picture*
                                    </label>
                                    {{form.image}}
                                    <div class="w-full border rounded-md bg-white border-dotted p-6">
                                        <div
                                            class="flex items-center flex-col md:flex-row gap-4 w-full justify-between">
                                            <div class="flex items-center space-x-4">
                                                <div id="img_container" data-image="{{form.image.value.url}}"
                                                    class="h-16 w-20 overflow-hidden rounded bg-gray-300">
                                                    <div id="no_image"></div>
                                                </div>
                                                <div class="space-y-1">
                                                    <p class="text-xs font-bold text-gray-500">Upload image
                                                        to illustrate your campaign</p>
                                                    <p class="text-xs font-light text-gray-500">SVG, PNG,
                                                        JPG, JPEG or GIF</p>
                                                </div>
                                            </div>
                                            <div id="pick_image"
                                                class="border p-2 cursor-pointer text-center text-black">
                                                <p class="text-sm">Browser</p>
                                            </div>
                                        </div>
                                    </div>

                                    <span
                                        class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.image.help_text}}</span>
                                    {% if form.image.errors %}
                                    <span
                                        class="text-[11px] text-red-500 block font-normal lowercase">{{form.image.errors.as_text}}</span>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="w-full lg:w-12/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label for="id_title">
                                        Title*
                                    </label>
                                    {{form.title}}
                                    <span
                                        class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.title.help_text}}</span>

                                </div>
                            </div>
                            <div class="w-full lg:w-6/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label for="id_category">
                                        category*
                                    </label>
                                    {{form.category}}
                                    <span
                                        class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.category.help_text}}</span>
                                </div>
                            </div>
                            <div class="w-full lg:w-6/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label for="id_target">
                                        target*
                                    </label>
                                    {{form.target}}
                                    <span
                                        class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.target.help_text}}</span>

                                </div>
                            </div>

                            <div class="w-full lg:w-6/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label for="id_end_date">
                                        Start date*
                                    </label>
                                    {{form.start_date}}
                                    <span
                                        class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.start_date.help_text}}</span>
                                </div>
                            </div>
                            <div class="w-full lg:w-6/12 px-4">
                                <div class="relative w-full mb-3">
                                    <label for="id_end_date">
                                        End date*
                                    </label>
                                    {{form.end_date}}
                                    <span class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.end_date.help_text}}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="w-full relative">
                        <h6 class="text-custom-h text-base mt-3 mb-6 font-bold uppercase">
                            About The Campaign
                        </h6>
                        <div class="flex flex-wrap">

                            <div class="w-full px-4">
                                <div class="relative w-full mb-3">
                                    <label for="id_details">
                                        Details about the campaign*
                                    </label>

                                    {{form.details}}
                                    <span
                                        class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.details.help_text}}</span>
                                    {% if form.details.errors %}
                                    <span
                                        class="text-[11px] text-red-500 block font-normal lowercase">{{form.details.errors.as_text}}</span>
                                    {% endif %}
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

                <hr class="mt-6 border-b-1 border-blueGray-300">
                <p class="text-sm text-custom-h font-medium mt-4">
                    By clicking submit, you are agreeing to our campaign <a href="{% url 'home:terms' %}" class="text-custom-primary">terms and
                        conditions</a>.
                </p>
                <div class="mt-3">
                    <div class="text-center inline-block h-12 bg-custom-primary w-[150px] rounded-md cursor-pointer">
                        <input type="submit" value="submit"
                            class="text-white w-full h-full cursor-pointer text-sm font-semibold" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}
{% block js %}
<script>
    window.onload = () => {
        const file_picker = document.querySelector("#id_image"),
            pick_image = document.querySelector("#pick_image")
        const no_image = document.querySelector("#no_image");
        const img_container = document.querySelector("#img_container")
        const img = document.querySelector("#img")

        if (img_container.getAttribute("data-image")) {

            img_container.removeChild(no_image);
            img_container.innerHTML += `
                    <img
                        src="${img_container.getAttribute("data-image")}"
                        alt="{{request.user.first_name}}"
                        class="w-full h-full object-cover"
                        id="img"
                    />
                `
        }
        pick_image.addEventListener('click', () => {
            file_picker.click()
        })

        file_picker.onchange = ({target}) => {

            var file = target.files[0]
            if (file) {
                // console.log(no_image)
                if (no_image) {

                    img_container.removeChild(no_image);
                    img_container.innerHTML += `
                    <img
                        src="${window.URL.createObjectURL(file)}"
                        alt="{{request.user.first_name}}"
                        class="w-full h-full object-cover"
                        id="img"
                    />
                `
                } else {
                    img.src = window.URL.createObjectURL(file)
                }

            } else {
                alert("no file selected")
            }

        };

    }

</script>
<script>
    
    $(document).ready(function () {
        // Initialize DateTimePicker for startDatetime
        $('#id_start_date').datetimepicker({
            format: 'Y-m-d H:i:s',
            minDate: 0,  // Set minimum date to the current date
            step: 15,   // Set the time step to 15 minutes (optional)
        });

        // Initialize DateTimePicker for endDatetime
        $('#id_end_date').datetimepicker({
            format: 'Y-m-d H:i:s',
            minDate: 0,  // Set minimum date to the current date
            step: 15,   // Set the time step to 15 minutes (optional)
        });
    });
</script>

{% endblock js %}