accounts/urls.py
from django.urls import path
from accounts.views.wallet import my_wallet
from accounts.views.account import *
from accounts.views.notification import subscribe, unsubscribe
from accounts.views.password import password_reset_request, password_change, passwordResetConfirm, password_reset_sent
from accounts.views.qualification import create_qualification, update_qualification, qualifications, delete_qualification
from accounts.views.relative import create_relative, update_relative, relatives, relative, delete_relative, relatives_api


app_name = "accounts"
urlpatterns = [
    path("", get_accounts, name="accounts"),
    path("dashboard", get_me, name="me"),
    path("register", register, name="register"),
    path('login', custom_login, name='login'),
    path('logout', custom_logout, name='logout'),
    path("dashboard/wallet", my_wallet, name="wallet"),
    path('register/success', activation_sent, name='success'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('confirm/email/<uidb64>/<token>', confirm_email, name='confirm-email'),

    path("password/reset", password_reset_request, name="password-reset"),
    path('password/success', password_reset_sent, name='password-reset-sent'),
    path('password/reset/<uidb64>/<token>', passwordResetConfirm, name='password-reset-confirm'),

    path('details/<username>', user_details, name="user"),
    path('update/subscribe', subscribe, name="subscribe"),
    path('update/unsubscribe', unsubscribe, name="unsubscribe"),
    path('update/profile', account_update, name="profile-update"),
    path('update/contact', general, name="contact-update"),
    path('update/password', password_change, name="password-update"),
    path('update/identitfication', identitification, name="verify"),
    path('update/social', add_social_links, name="update-social-links"),

    path('qualifications', qualifications, name="qualifications"),
    path('qualification/update/<id>', update_qualification, name="update-qualification"),
    path('qualification/delete/<id>', delete_qualification, name="delete-qualification"),
    path('qualification/create', create_qualification, name="create-qualification"),

    path('relatives', relatives, name="relatives"),
    path('relatives/api', relatives_api, name="relatives-api"),
    path('relatives/details/<uuid:id>', relative, name="relative"),
    path('relative/update/<uuid:id>', update_relative, name="update-relative"),
    path('relative/delete/<uuid:id>', delete_relative, name="delete-relative"),
    path('relative/create', create_relative, name="create-relative"),

]

company/urls.py
from django.urls import path

from company.views.accounts import all_accounts, get_account_detals
from company.views.blogs import all_blogs
from company.views.campaigns import all_campaigns, campaign_details
from company.views.contributions import all_contributions, delete_contribution, contribution_details
from company.views.events import all_events, event_details
from company.views.home import earnings, view_order
from company.views.ticket_orders import all_ticket_orders, ticket_order_details, delete_ticket_order


app_name = "company"
urlpatterns = [
    path("", earnings, name="earnings"),
    path("earning/<order_uuid>", view_order, name="view-earning"),
    path("accounts", all_accounts, name="all-accounts"),
    path("accounts/<username>", get_account_detals, name="get-account-details"),
    path("campaigns", all_campaigns, name="all-campaigns"),
    path("campaign/<slug:campaign_slug>", campaign_details, name="campaign-details"),
    path("accounts/campaigns/<username>", all_campaigns, name="all-campaigns-by-username"),
    path("events", all_events, name="all-events"),
    path("event/<slug:event_slug>", event_details, name="event-details"),
    path("accounts/events/<username>", all_events, name="all-events-by-username"),
    path("contributions", all_contributions, name="all-contributions"),
    path("contributions/<contribution_id>", contribution_details, name="contribution"),
    path("contribution/delete/<uuid:contribution_id>", delete_contribution, name="delete-contribution"),
    path("ticket-orders", all_ticket_orders, name="all-ticket-orders"),
    path("ticket-orders/<order_id>", ticket_order_details, name="order"),
    path("ticket-orders/delete/<uuid:order_id>", delete_ticket_order, name="cancel-ticket-order"),
    path("blogs", all_blogs, name="all-blogs"),
]

events/urls.py
from django.urls import path
from events.views.event import create_event, event_details, events, update_event, delete_event
from events.views.order import create_ticket_order, add_guest_details, ticket_order, ticket_orders, cancel_ticket_order
from events.views.ticket_type import create_ticket_types, update_ticket_type, get_event_ticket_types, delete_ticket_type
from events.views.manage import manage_event, manage_events, manage_ticket_order, manage_ticket_orders, generate_guest_list, generate_ticket

app_name = "events"
urlpatterns = [
    path("", events, name="events"),
    path("<slug:category_slug>", events, name="events-by-category"),
    path("event/create", create_event, name="create-event"),
    path("event/details/<slug:event_slug>", event_details, name="event-details"),
    path("event/update/<slug:event_slug>", update_event, name="update-event"),
    path("event/delete/<slug:event_slug>", delete_event, name="delete-event"),
    path("event/manage", manage_events, name="manage-events"),
    path("event/manage/<slug:event_slug>", manage_event, name="manage-event"),

    path("ticket-types/<event_id>", get_event_ticket_types, name="event-ticket-types"),
    path("ticket-types/create/<event_id>", create_ticket_types, name="create-ticket-types"),
    path("ticket-types/update/<slug:event_slug>/<uuid:ticket_type_id>", update_ticket_type, name="update-ticket-type"),
    path("ticket-types/delete/<slug:event_slug>/<uuid:ticket_type_id>", delete_ticket_type, name="delete-ticket-type"),

    path("orders/all", ticket_orders, name="all-ticket-orders"),
    path("orders/all/<event_id>", ticket_orders, name="ticket-orders"),
    path("order/all/<slug:event_slug>/<uuid:order_id>", ticket_order, name="order"),
    path("order/generate/guest/<uuid:event_id>", generate_guest_list, name="generate-guest-list"),
    path("order/create/<slug:event_slug>", create_ticket_order, name="create-ticket-order"),
    path("order/cancel/<uuid:order_id>", cancel_ticket_order, name="cancel-ticket-order"),
    path("order/guest/<uuid:ticket_order_id>", add_guest_details, name="add-guests"),
    path("order/manage", manage_ticket_orders, name="manage-ticket-orders"),
    path("order/manage/<uuid:order_id>", manage_ticket_order, name="manage-ticket-order"),
    path("order/generate/ticket/<uuid:order_id>/<uuid:ticket_id>", generate_ticket, name="generate-ticket")

    
    
]

home/urls.py
from django.urls import path
from home.views import home, search, news, post_details, help, contact, terms_and_conditions

app_name = "home"
urlpatterns = [
    path("", home, name="home"),
    path("privacy", terms_and_conditions, name="terms"),
    path("privacy/<slug:terms_slug>", terms_and_conditions, name="privacy"),
    path("faq", help, name="help"),
    path("contact", contact, name="contact"),
    path("search", search, name="search"),
    path("posts", news, name="news"),
    path("posts/<slug:category_slug>", news, name="news-category"),
    path("posts/<slug:category_slug>/<slug:post_slug>", post_details, name="news-details")
]

ndwandwafam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("campaigns/", include("campaigns.urls", namespace="campaigns")),
    path("events/", include("events.urls", namespace="events")),
    path("payments/", include("payments.urls", namespace="payments")),
    path("company/", include("company.urls", namespace="company")),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/views/notification.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from accounts.forms.profile_forms import SubscribeForm

from accounts.models import MailingGroupModel, SubscribeModel

@login_required
def subscribe(request):
    mailinggroups = MailingGroupModel.objects.all()
    if request.method == 'POST':
        form = SubscribeForm(request.POST)
        if form.is_valid():
            selected = form.cleaned_data["mailinggroups"]
            for group in MailingGroupModel.objects.all():
                group.subscribers.remove(request.user)
                
            if selected.count() == 0:
                messages.success(request, 'You successfully unsubscribe from all Ndwandwa family foundation mailing groups')
                return redirect('accounts:subscribe')
            
            for group in MailingGroupModel.objects.all():
                group.subscribers.remove(request.user)

            for group in form.cleaned_data["mailinggroups"]:
                
                subscribed, created = SubscribeModel.objects.get_or_create(user=request.user, mailinggroup=group)
                if created:
                    messages.success(request, f"You have successfully subscribed to {group.title} mailing group")
            return render(request, "accounts/notification/index.html", {"mailinggroups": mailinggroups, "form": form})
        
        else:
            messages.error(request, "There is error, please fix it below")
            return render(request, "accounts/notification/index.html", {"mailinggroups": mailinggroups, "form": form})
    form = SubscribeForm()
    return render(request, "accounts/notification/index.html", {"mailinggroups": mailinggroups, "form": form})

def unsubscribe(request):
    try:
        for group in MailingGroupModel.objects.all():
            group.subscribers.remove(request.user)

        messages.success(request, 'You successfully unsubscribe from all Ndwandwa family foundation mailing groups')
        return redirect('accounts:subscribe')
    except get_user_model().DoesNotExist:
        messages.success(request, 'You successfully unsubscribe from all Ndwandwa family foundation mailing groups')

        return redirect('accounts:subscribe')
    
def create_mailing_group(request):
    form = None
    if request.method == 'POST':
        form = "MailingGroupForm(request.POST)"
        if form:
            pass

accounts/views/password.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.http import urlsafe_base64_decode
from django.utils.encoding import force_str
from accounts.utils import send_password_reset_email
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.shortcuts import render, redirect
from accounts.tokens import account_activation_token
from accounts.decorators import user_not_authenticated
from accounts.utils import send_verification_email
import logging

email_logger = logging.getLogger("emails")
account_logger = logging.getLogger("accounts")

@login_required
def password_change(request):
    user = request.user
    template = 'accounts/account/password/change_password.html'
    if request.method == 'POST':
        form = PasswordChangeForm(user, request.POST)
        if form.is_valid():
            form.save()

            messages.success(request, "Your password has been changed")
            return redirect('accounts:password-update')
        else:
            messages.error(request, "Your password was not changed. Fix errors below")
            return render(request, template, {'form': form})

    form = PasswordChangeForm(user)
    return render(request, template, {'form': form})

@user_not_authenticated
def password_reset_request(request):
    try:
        if request.method == 'POST':
            form = PasswordResetForm(request.POST)
            if form.is_valid():
                user_email = form.cleaned_data['email']
                user = get_user_model().objects.get(email=user_email)
                if not user.is_active:
                    messages.error(request, f"Sorry your account is not active. We have sent account activation email to your email {user.email}")
                    sent = send_verification_email(user, request)
                    if sent:
                        return redirect("accounts:login")

                sent = send_password_reset_email(user, request)
                if not sent:
                    email_logger.error(f"Password reset email to {user.get_full_name()} was not sent")

                messages.success(request, "Password reset email was successfully sent")
                return redirect("accounts:password-reset-sent")
            else:
                return render(request, "accounts/account/password/pwd_reset_form.html", {"form": form})
    except get_user_model().DoesNotExist as ex:
        account_logger.error(f"User not found - trying to request email reset - {ex}")
        messages.success(request, "Password reset email was successfully sent")
        return redirect("accounts:password-reset-sent")

    except Exception as ex:
        account_logger.error(ex)
        messages.success(request, "Password reset email was successfully sent")
        return redirect("accounts:password-reset-sent")
    
    form = PasswordResetForm()
    return render(
        request=request, 
        template_name="accounts/account/password/pwd_reset_form.html", 
        context={"form": form}
        )

def password_reset_sent(request):
    return render(request, "accounts/account/password/password_email_sent.html")

def passwordResetConfirm(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        if request.method == 'POST':
            form = SetPasswordForm(user, request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Your password has been set. You may go ahead and <b>log in </b> now.")
                return redirect('accounts:login')
            else:
                return render(request, 'accounts/account/password/pwd_reset_confirm.html', {'form': form})

        form = SetPasswordForm(user)
        return render(request, 'accounts/account/password/pwd_reset_confirm.html', {'form': form})
    else:
        messages.error(request, "Link is expired")
        return redirect("accounts:reset-password")

accounts/views/qualification.py
from accounts.models import QualificationModel
from accounts.forms.profile_forms import QualificationForm, QualificationUpdateForm
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages

def validate_qualification(clean, request):
    name = clean.get("title", None)
    last_name = clean.get("institution", None)
    other_surname = clean.get("year", None)
    qual_type = clean.get("qualification_type", None)
    qualification = request.user.qualifications.filter(title = name, institution = last_name, year = other_surname, qualification_type= qual_type).exists()
    return qualification

def qualifications(request):
    template = "accounts/qualification/list.html"
    queryset = QualificationModel.objects.filter(owner = request.user)

    return render(request, template, {"qualifications": queryset})

def create_qualification(request):
    template = "accounts/qualification/create.html"
    if request.method == 'POST':
        form = QualificationForm(request.POST)
        if form.is_valid():
            clean = form.cleaned_data
            qualification_found = validate_qualification(clean, request)
            if qualification_found:
                messages.error(request, "Qualification with following details already exists")
                return render(request, template, {"form": form})
            
            qualification = form.save(commit=False)
            qualification.owner = request.user
            qualification.save()
            messages.success(request, "Your qualification was added successfully")
            return redirect("accounts:qualifications")
        else:
            return render(request, template, {"form": form})
    
    form = QualificationForm()
    return render(request, template, {"form": form})

def update_qualification(request, id):
    template = "accounts/qualification/update.html"
    model = get_object_or_404(QualificationModel, owner=request.user, id=id)
    if request.method == 'POST':
        form = QualificationUpdateForm(instance=model, data=request.POST)
        if form.is_valid():
            qualification = form.save(commit=False)
            qualification.save()
            messages.success(request, "Your qualification was added successfully")
            return redirect("accounts:qualifications")
        else:
            return render(request, template, {"form": form})
    
    form = QualificationUpdateForm(instance=model)
    return render(request, template, {"form": form})

def delete_qualification(request, id):
    model = get_object_or_404(QualificationModel, owner=request.user, id=id)
    model.delete()
    return redirect("accounts:qualifications")

accounts/templates/accounts/wallet/details.html
{% extends '_manage.html' %}
{% load static %}

{% block title %}{{user.username}}{% endblock title %}

{% block accountblock %}
<section class="w-full bg-custom-bg py-10 relative block">
    {% include "includes/messages.html" %}
    {% if infor %}
      
    
    <div class="flex bg-blue-100 rounded-lg p-4 mb-4 text-sm text-blue-700" role="alert">
        <svg class="w-5 h-5 inline mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
                d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
                clip-rule="evenodd"></path>
        </svg>
        <div>
            {{ infor|safe|escape }}
        </div>
    </div>
    {% endif %}
    <div class="">
        <div class="relative overflow-hidden block">
            <div class="grid items-center gap-7 mb-7 grid-cols-1 sm:grid-cols-2 md:grid-cols-3">
                <div class="flex items-center p-8 bg-white shadow rounded-lg">
                    <div
                        class="inline-flex flex-shrink-0 items-center justify-center h-16 w-16 text-purple-600 bg-purple-100 rounded-full mr-6">
                        <svg width="30" height="30" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                            class="stroke-current text-blue-800 dark:text-gray-800 transform transition-transform duration-500 ease-in-out">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z">
                            </path>
                        </svg>
                    </div>
                    <div>
                        <span class="block text-2xl font-bold">R{{wallet.balance}}</span>
                        <span class="block text-gray-500">Balance</span>
                    </div>
                </div>
                
                <div class="flex items-center p-8 bg-white shadow rounded-lg">
                    <div
                        class="inline-flex flex-shrink-0 items-center justify-center h-16 w-16 text-purple-600 bg-purple-100 rounded-full mr-6">
                        <svg width="30" height="30" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                            class="stroke-current text-blue-800 dark:text-gray-800 transform transition-transform duration-500 ease-in-out">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z"></path>
                        </svg>

                    </div>
                    <div>
                        <span class="block text-2xl font-bold">{{contributions|length}}</span>
                        <span class="block text-gray-500">Contributions</span>
                    </div>
                </div>
                <div class="flex items-center p-8 bg-white shadow rounded-lg">
                    <div
                        class="inline-flex flex-shrink-0 items-center justify-center h-16 w-16 text-purple-600 bg-purple-100 rounded-full mr-6">
                        <svg width="30" height="30" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                            class="stroke-current text-blue-800 dark:text-gray-800 transform transition-transform duration-500 ease-in-out">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"></path>
                        </svg>
                    </div>
                    <div>
                        <span class="block text-2xl font-bold">{{ticketorders|length}}</span>
                        <span class="block text-gray-500">Ticket Orders</span>
                    </div>
                </div>
            </div>
            <div class="w-full">
                <div class="py-7 mb-4">
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 p-2">
                        <div class="bg-white p-4 rounded-md">
                            <h2 class="text-gray-500 text-lg font-semibold pb-4">Latest Contributions</h2>
                            <div class="my-1"></div>

                            <table class="w-full text-left table-auto min-w-max">
                                <thead>
                                    <tr>
                                        <th class="p-4 border-y border-blue-gray-100 bg-blue-gray-50/50">
                                            <p
                                                class="block font-sans text-sm antialiased font-normal leading-none text-blue-gray-900 opacity-70">
                                                Contr. ID
                                            </p>
                                        </th>
                                        <th class="p-4 border-y border-blue-gray-100 bg-blue-gray-50/50">
                                            <p class="block font-sans text-sm antialiased font-normal leading-none text-blue-gray-900 opacity-70">
                                                Amount
                                            </p>
                                        </th>

                                        <th class="p-4 border-y border-blue-gray-100 bg-blue-gray-50/50">
                                            <p
                                                class="block font-sans text-sm antialiased font-normal leading-none text-blue-gray-900 opacity-70">
                                                Status
                                            </p>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in contributions|slice:":5" %}
                                    <tr>
                                        <td class="p-4 border-b border-blue-gray-50">
                                            <a href="{{order.get_absolute_url}}" class="block font-sans text-sm antialiased font-normal leading-normal text-blue-gray-900">
                                                {{order.order_number}}
                                            </a>
                                        </td>
                                        <td class="p-4 border-b border-blue-gray-50">
                                            <p class="block font-sans text-sm antialiased font-normal leading-normal text-blue-gray-900">
                                                R{{order.total_amount}}
                                            </p>
                                        </td>
                                        <td class="p-2 border-b border-blue-gray-50">
                                            <div class="w-max">
                                                <div
                                                    class="relative grid items-center px-2 py-1 font-sans text-xs font-bold {% if order.paid == 'PAID' %} bg-green-500/20 text-green-900{% elif order.paid == 'PENDING' %}bg-amber-500/20 text-amber-900 {% else %}bg-red-500/20 text-red-900{% endif %}  uppercase rounded-md select-none whitespace-nowrap ">
                                                    <span class="">{{order.paid}}</span>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>

                            {% if contributions.count == 5 %}
                            <div class="text-right mt-4">
                                <a href="{% url 'campaigns:all-contributions' %}"
                                    class="bg-custom-h hover:bg-custom-h text-white font-semibold py-2 px-4 rounded">
                                    View more
                                </a>
                            </div>
                            {% endif %}
                        </div>
                        <div class="bg-white p-4 rounded-md">
                            <h2 class="text-gray-500 text-lg font-semibold pb-4">Latest Ticket Orders</h2>
                            <div class="my-1"></div>

                            <table class="w-full text-left table-auto min-w-max">
                                <thead>
                                    <tr>
                                        <th class="p-4 border-y border-blue-gray-100 bg-blue-gray-50/50">
                                            <p class="block font-sans text-sm antialiased font-normal leading-none text-blue-gray-900 opacity-70">
                                                Contr. ID
                                            </p>
                                        </th>
                                        <th class="p-4 border-y border-blue-gray-100 bg-blue-gray-50/50">
                                            <p class="block font-sans text-sm antialiased font-normal leading-none text-blue-gray-900 opacity-70">
                                                Amount
                                            </p>
                                        </th>
                            
                                        <th class="p-4 border-y border-blue-gray-100 bg-blue-gray-50/50">
                                            <p class="block font-sans text-sm antialiased font-normal leading-none text-blue-gray-900 opacity-70">
                                                Status
                                            </p>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in ticketorders|slice:":5" %}
                                    <tr>
                                        <td class="p-4 border-b border-blue-gray-50">
                                            <a href="{{order.get_absolute_url}}"
                                                class="block font-sans text-sm antialiased font-normal leading-normal text-blue-gray-900">
                                                {{order.order_number}}
                                            </a>
                                        </td>
                                        <td class="p-4 border-b border-blue-gray-50">
                                            <p class="block font-sans text-sm antialiased font-normal leading-normal text-blue-gray-900">
                                                R{{order.total_price}}
                                            </p>
                                        </td>
                                        <td class="p-2 border-b border-blue-gray-50">
                                            <div class="w-max">
                                                <div
                                                    class="relative grid items-center px-2 py-1 font-sans text-xs font-bold {% if order.paid == 'PAID' %} bg-green-500/20 text-green-900{% elif order.paid == 'PENDING' %}bg-amber-500/20 text-amber-900 {% else %}bg-red-500/20 text-red-900{% endif %}  uppercase rounded-md select-none whitespace-nowrap ">
                                                    <span class="">{{order.paid}}</span>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            {% if ticketorders.count > 5 %}
                            <div class="text-right mt-4">
                                <a href="{% url 'events:all-ticket-orders' %}"
                                    class="bg-custom-h hover:bg-custom-h text-white font-semibold py-2 px-4 rounded">
                                    View more
                                </a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock accountblock %}