accounts/urls.py
from django.urls import path
from accounts.views.wallet import my_wallet
from accounts.views.account import *
from accounts.views.notification import subscribe, unsubscribe
from accounts.views.password import password_reset_request, password_change, passwordResetConfirm, password_reset_sent
from accounts.views.qualification import create_qualification, update_qualification, qualifications, delete_qualification
from accounts.views.relative import create_relative, update_relative, relatives, relative, delete_relative, relatives_api


app_name = "accounts"
urlpatterns = [
    path("", get_accounts, name="accounts"),
    path("dashboard", get_me, name="me"),
    path("register", register, name="register"),
    path('login', custom_login, name='login'),
    path('logout', custom_logout, name='logout'),
    path("dashboard/wallet", my_wallet, name="wallet"),
    path('register/success', activation_sent, name='success'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('confirm/email/<uidb64>/<token>', confirm_email, name='confirm-email'),

    path("password/reset", password_reset_request, name="password-reset"),
    path('password/success', password_reset_sent, name='password-reset-sent'),
    path('password/reset/<uidb64>/<token>', passwordResetConfirm, name='password-reset-confirm'),

    path('details/<username>', user_details, name="user"),
    path('update/subscribe', subscribe, name="subscribe"),
    path('update/unsubscribe', unsubscribe, name="unsubscribe"),
    path('update/profile', account_update, name="profile-update"),
    path('update/contact', general, name="contact-update"),
    path('update/password', password_change, name="password-update"),
    path('update/identitfication', identitification, name="verify"),
    path('update/social', add_social_links, name="update-social-links"),

    path('qualifications', qualifications, name="qualifications"),
    path('qualification/update/<id>', update_qualification, name="update-qualification"),
    path('qualification/delete/<id>', delete_qualification, name="delete-qualification"),
    path('qualification/create', create_qualification, name="create-qualification"),

    path('relatives', relatives, name="relatives"),
    path('relatives/api', relatives_api, name="relatives-api"),
    path('relatives/details/<uuid:id>', relative, name="relative"),
    path('relative/update/<uuid:id>', update_relative, name="update-relative"),
    path('relative/delete/<uuid:id>', delete_relative, name="delete-relative"),
    path('relative/create', create_relative, name="create-relative"),

]

home/urls.py
from django.urls import path
from home.views import home, search, news, post_details, help, contact, terms_and_conditions

app_name = "home"
urlpatterns = [
    path("", home, name="home"),
    path("privacy", terms_and_conditions, name="terms"),
    path("privacy/<slug:terms_slug>", terms_and_conditions, name="privacy"),
    path("faq", help, name="help"),
    path("contact", contact, name="contact"),
    path("search", search, name="search"),
    path("posts", news, name="news"),
    path("posts/<slug:category_slug>", news, name="news-category"),
    path("posts/<slug:category_slug>/<slug:post_slug>", post_details, name="news-details")
]

ndwandwafam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("campaigns/", include("campaigns.urls", namespace="campaigns")),
    path("events/", include("events.urls", namespace="events")),
    path("payments/", include("payments.urls", namespace="payments")),
    path("company/", include("company.urls", namespace="company")),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.dispatch import receiver
from taggit.managers import TaggableManager
from django.template.defaultfilters import slugify
from django.utils.safestring import mark_safe
from django.utils.translation import gettext as _
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import pre_delete, post_save
from accounts.utils import (TITLE_CHOICES, WALLET_STATUS, Gender, RelationshipSides, StatusChoices, IdentityNumberChoices, RelationShip, QualificationType, 
                            handle_profile_upload, handle_relativeprofile_upload, handle_verification_docs_upload, verify_rsa_phone,
                            validate_twitter_link, validate_fcbk_link, validate_in_link, validate_insta_link)
from tinymce.models import HTMLField

from campaigns.utils import PaymentStatus


PHONE_VALIDATOR = verify_rsa_phone()

class AbstractProfile(models.Model):
    address_one = models.CharField(max_length=300, blank=True, null=True)
    address_two = models.CharField(max_length=300, blank=True, null=True)
    city = models.CharField(max_length=300, blank=True, null=True)
    province = models.CharField(max_length=300, blank=True, null=True)
    country = models.CharField(max_length=300, default="South Africa")
    zipcode = models.BigIntegerField(blank=True, null=True)
    address_id = models.CharField(max_length=300, null=True, blank=True)

    facebook = models.URLField(validators=[validate_fcbk_link], blank=True, null=True)
    twitter = models.URLField(validators=[validate_twitter_link], blank=True, null=True)
    instagram = models.URLField(validators=[validate_insta_link], blank=True, null=True)
    linkedIn = models.URLField(validators=[validate_in_link], blank=True, null=True)

    class Meta:
        abstract = True

class AbstractCreate(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, unique=True, editable=False, db_index=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class CompanyModel(AbstractCreate, AbstractProfile):
    support_email = models.EmailField(max_length=254, unique=True)
    phone = models.CharField(help_text=_("Enter your cellphone number"), max_length=15, validators=[PHONE_VALIDATOR], unique=True, null=True, blank=True)
    
    class Meta:
        verbose_name = "Company Details"
        verbose_name_plural = "Company Details"
    
    def __str__(self):
        return "Ndwandwa Family Foundation"
    
class WalletModel(AbstractCreate):
    name = models.CharField(max_length=250)
    balance = models.DecimalField(max_digits=1000, decimal_places=2, default=0.00)
    owner = models.OneToOneField("CustomUserModel", on_delete=models.CASCADE, related_name="my_wallet")
    status = models.CharField(max_length=150, choices=WALLET_STATUS, default=WALLET_STATUS[0])
    cleared_date = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = _("Wallet")
        verbose_name_plural = _("Wallets")
        ordering = ["-created"]

    def request_payout_details(self):
        pass

    def clear_account(self):
        self.balance = 0

    def __str__(self):
        return self.name
    
class CustomUserModel(AbstractUser, AbstractProfile):
    profile_image = models.ImageField(help_text=_("Upload profile image"), upload_to=handle_profile_upload, null=True, blank=True, default="images/global/no-image-available.webp")
    title = models.CharField(max_length=30, choices=TITLE_CHOICES)
    maiden_name = models.CharField(help_text=_("Enter your maiden name"), max_length=300, blank=True, null=True)
    phone = models.CharField(help_text=_("Enter your cellphone number"), max_length=15, validators=[PHONE_VALIDATOR], unique=True, null=True, blank=True)
    occupation = models.CharField(default='N/A',help_text=_("Enter your current employment"), max_length=500, blank=True, null=True)
    biography = models.TextField(blank=True)
    professional_affiliations = models.CharField(default='N/A',help_text=_("Enter your professional affiliations"), max_length=700, blank=True, null=True)
    identity_choice = models.CharField(help_text=_("Select your identity document"), max_length=100, choices=IdentityNumberChoices.choices, default=IdentityNumberChoices.ID_NUMBER)
    identity_number = models.CharField(unique=True, max_length=13, null=True, blank=True)
    verification_status = models.CharField(max_length=100, choices=StatusChoices.choices, default=StatusChoices.NOT_APPROVED)
    hobbies = TaggableManager(blank=True)
    is_technical = models.BooleanField(default=False)
    is_email_activated = models.BooleanField(default=False)
    is_paid = models.CharField(max_length=40, choices=PaymentStatus.choices, default=PaymentStatus.NOT_PAID)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

  
    class Meta:
        verbose_name = _("Account")
        verbose_name_plural = _("Accounts")
        ordering = ["-created"]
    
    def get_absolute_url(self):
        return reverse("accounts:user", kwargs={"username": self.username})
    
    def image_tag(self):
        if self.profile_image.url is not None:
            return mark_safe(f"<img src={self.profile_image.url} alt={self.first_name}-image height='60' width='60' style='border-radius: 50%; height: 60px; width: 60px;' />")
        return ""
    
    def address(self):
        if self.address_one and self.city and self.province and self.country:
            if self.address_two:
                return f"{self.address_one}, {self.address_two}, {self.city}, {self.province}, {self.country}"
            else:
                return f"{self.address_one}, {self.city}, {self.province}, {self.country}"
        else:
            return "No address"
    
    def contact_details(self):
        return mark_safe(f"""
            <div style="display: flex; align-items: center; background-color: #fff;;">
                <a href="mailto:{self.email}" style="margin: 0rem 1rem;">{self.email}</a>
                <a href="tel:{self.phone}" style="margin: 0rem 1rem;">{self.phone}</a>
            </div>
            <div style="display: flex; align-items: center; background-color: #fff;;">
                <a href="{self.facebook}" style="margin: 0rem 1rem;">{self.facebook}</a>
                <a href="{self.twitter}" style="margin: 0rem 1rem;">{self.twitter}</a>
            </div>
        """)

    def identity_information(self):
        return f"{self.identity_number} - {self.identity_choice}"

    def full_names(self):
        if self.maiden_name != None:
            return f"{self.title} {self.first_name} {self.last_name} {self.maiden_name}"
        else:
            return f"{self.title} {self.first_name} {self.last_name}"
    
    def employment_details(self):
        if self.occupation and self.professional_affiliations:
            return f"{self.occupation} - {self.professional_affiliations}"
        elif self.occupation:
            return f"{self.occupation}"
        elif self.professional_affiliations:
            return f"No occupation - {self.professional_affiliations}"
        else:
            return "No occupation"
    
    def __str__(self) -> str:
        if self.first_name:
            return self.first_name
        else:
            return f"{self.username}"
    
class IdentityVerificationModel(AbstractCreate):
    identity_image =  models.ImageField(upload_to=handle_verification_docs_upload, null=False, help_text=_("Please take a selfie while holding an official identification document(ID Card, Passport)"))
    identitybook_image = models.ImageField(upload_to=handle_verification_docs_upload, null=False, help_text=_("Please take a picture of your official identification document(ID Card, Passport, drivers license, etc)"))
    user = models.OneToOneField(CustomUserModel, related_name="verification", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Identity Verification")
        verbose_name_plural = _("Identity Verifications")
        ordering = ["-created"]

    def get_absolute_url(self):
        return reverse("accounts:verify")
    
    def __str__(self) -> str:
        return f"{self.user.get_full_name()} - Identity verification data"

class RelativeModel(AbstractCreate):
    profile_image = models.ImageField(help_text=_("Upload relative's profile image"), upload_to=handle_relativeprofile_upload, null=True, blank=True)
    title = models.CharField(max_length=30, choices=TITLE_CHOICES)
    full_name = models.CharField(help_text=_("Enter your relative's name"), max_length=300)
    maiden_name = models.CharField(help_text=_("Enter your relative's maiden name"), max_length=300, blank=True, null=True)
    surname = models.CharField(help_text=_("Enter your relative's surname"), max_length=300)
    date_of_birth = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
    date_of_death = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
    relationship = models.CharField(max_length=300, choices=RelationShip.choices, default=RelationShip.OTHER)
    phone = models.CharField(help_text=_("Enter relative's cell phone number"), max_length=15,  validators=[PHONE_VALIDATOR], null=True, blank=True)
    relative = models.ForeignKey(CustomUserModel, related_name="relatives", on_delete=models.CASCADE)
    gender = models.CharField(help_text=_("Select relative's gender"), max_length=15, choices=Gender.choices)
    relative_side = models.CharField(max_length=300, choices=RelationshipSides.choices, blank=True, null=True)
    description = models.TextField(blank=True, null=True, help_text=_("Provide a small description of this relative, e.g His/Her Children"))

    class Meta:
        verbose_name = 'Relative'
        verbose_name_plural = 'Relatives'

accounts/views/notification.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from accounts.forms.profile_forms import SubscribeForm

from accounts.models import MailingGroupModel, SubscribeModel

@login_required
def subscribe(request):
    mailinggroups = MailingGroupModel.objects.all()
    if request.method == 'POST':
        form = SubscribeForm(request.POST)
        if form.is_valid():
            selected = form.cleaned_data["mailinggroups"]
            for group in MailingGroupModel.objects.all():
                group.subscribers.remove(request.user)
                
            if selected.count() == 0:
                messages.success(request, 'You successfully unsubscribe from all Ndwandwa family foundation mailing groups')
                return redirect('accounts:subscribe')
            
            for group in MailingGroupModel.objects.all():
                group.subscribers.remove(request.user)

            for group in form.cleaned_data["mailinggroups"]:
                
                subscribed, created = SubscribeModel.objects.get_or_create(user=request.user, mailinggroup=group)
                if created:
                    messages.success(request, f"You have successfully subscribed to {group.title} mailing group")
            return render(request, "accounts/notification/index.html", {"mailinggroups": mailinggroups, "form": form})
        
        else:
            messages.error(request, "There is error, please fix it below")
            return render(request, "accounts/notification/index.html", {"mailinggroups": mailinggroups, "form": form})
    form = SubscribeForm()
    return render(request, "accounts/notification/index.html", {"mailinggroups": mailinggroups, "form": form})

def unsubscribe(request):
    try:
        for group in MailingGroupModel.objects.all():
            group.subscribers.remove(request.user)

        messages.success(request, 'You successfully unsubscribe from all Ndwandwa family foundation mailing groups')
        return redirect('accounts:subscribe')
    except get_user_model().DoesNotExist:
        messages.success(request, 'You successfully unsubscribe from all Ndwandwa family foundation mailing groups')

        return redirect('accounts:subscribe')
    
def create_mailing_group(request):
    form = None
    if request.method == 'POST':
        form = "MailingGroupForm(request.POST)"
        if form:
            pass

accounts/templates/accounts/qualification/create.html
{% extends '_manage.html' %}
{% load static %}

{% block title %}Add Qualification{% endblock title %}

{% block accountblock %}
<div class='w-full h-full'>

    <div class="w-full mx-auto bg-white">
        <div class="space-y-4">
            {% include "includes/errors.html" %}
            <div class="md:px-4">
                
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <h6 class="text-custom-h text-base mt-3 mb-6 font-bold uppercase">
                        Qualifications Information
                    </h6>
                    <div class="flex flex-wrap space-y-3 md:space-y-0">
                        <div class="w-full lg:w-6/12 md:px-4">
                            <div class="relative w-full mb-3">
                                <label for="id_title"
                                    class="block text-custom-h font-semibold text-sm capitalize mb-2"
                                    htmlfor="grid-password">
                                    Title*
                                </label>
                                <input id="id_title" name="title" required maxlength="300" type="text"
                                    class="block p-3 md:text-base w-full text-sm text-custom-h outline-none bg-gray-50 rounded-lg border border-gray-300 focus:ring-custom-primary placeholder:text-gray-400 focus:border-custom-primary ease-linear transition-all duration-150">
                                <span
                                    class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.title.help_text}}</span>

                            </div>
                        </div>
                        <div class="w-full lg:w-6/12 md:px-4">
                            <div class="relative w-full mb-3">
                                <label for="id_year"
                                    class="block text-custom-h font-semibold text-sm capitalize mb-2"
                                    htmlfor="grid-password">
                                    Year range*
                                </label>
                                <input id="id_year" name="year" maxlength="300" type="text"
                                    class="block p-3 md:text-base w-full text-sm text-custom-h outline-none bg-gray-50 rounded-lg border border-gray-300 focus:ring-custom-primary placeholder:text-gray-400 focus:border-custom-primary ease-linear transition-all duration-150">
                                <span
                                    class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.year.help_text}}</span>

                            </div>
                        </div>
                        <div class="w-full lg:w-6/12 md:px-4">
                            <div class="relative w-full mb-3">
                                <label for="id_institution"
                                    class="block text-custom-h font-semibold text-sm capitalize mb-2"
                                    htmlfor="grid-password">
                                    institution*
                                </label>
                                <input id="id_institution" name="institution" maxlength="300" type="text"
                                    class="block p-3 md:text-base w-full text-sm text-custom-h outline-none bg-gray-50 rounded-lg border border-gray-300 focus:ring-custom-primary placeholder:text-gray-400 focus:border-custom-primary ease-linear transition-all duration-150">

                                <span
                                    class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.institution.help_text}}</span>

                            </div>
                        </div>
                        <div class="w-full lg:w-6/12 md:px-4">
                            <div class="relative w-full mb-3">
                                <label for="id_qualification_type"
                                    class="block text-custom-h font-semibold text-sm capitalize mb-2"
                                    htmlfor="grid-password">
                                    Describe your qualification*
                                </label>
                                {{form.qualification_type}}
                                <span
                                    class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.qualification_type.help_text}}</span>

                            </div>
                        </div>
                    </div>

                    <div class="text-center mt-6 inline-block h-12 bg-custom-primary w-[150px] rounded-md cursor-pointer">
                        <input type="submit" value="submit"
                            class="text-white w-full h-full cursor-pointer text-sm font-semibold" />
                    </div>

                </form>
            </div>
        </div>
    </div>

</div>
{% endblock accountblock %}

{% block javascript %}
<script>

</script>

{% endblock javascript %}

accounts/templates/accounts/qualification/list.html
{% extends '_manage.html' %}
{% load static %}

{% block title %}Education{% endblock title %}

{% block accountblock %}
<div class="relative block bg-white">
    <div class=" py-2 overflow-x-auto">
        <div
            class="align-middle rounded-tl-lg rounded-tr-lg inline-block w-full py-4 overflow-hidden bg-white px-12">
            <div class="flex justify-between">
                
                <div>
                    <a href="{% url 'accounts:create-qualification' %}"
                            class="px-5 py-2 border-custom-h border text-custom-h  rounded transition duration-300 hover:bg-custom-h hover:text-white focus:outline-none">Add qualification</a>
                </div>
            </div>
        </div>
        <div
            class="align-middle inline-block min-w-full overflow-hidden bg-white px-8 pt-3 rounded-bl-lg rounded-br-lg">
            <table class="min-w-full">
                <thead>
                    <tr>
                        <th
                            class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-custom-h tracking-wider">
                            Title</th>
                        <th
                            class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-custom-h tracking-wider">
                            institution</th>

                        <th
                            class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-custom-h tracking-wider">
                            Ranking</th>
                        <th
                            class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-custom-h tracking-wider">
                            Year</th>
                        <th class="px-6 py-3 border-b-2 border-gray-300"></th>
                    </tr>
                </thead>
                <tbody class="bg-white">

                    {% for qualification in qualifications %}
                    <tr>

                        <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-500">
                            <div class="text-sm leading-5 text-custom-primary">{{qualification.title}}</div>
                        </td>
                        <td
                            class="px-6 py-4 whitespace-no-wrap border-b text-custom-primary border-gray-500 text-sm leading-5">
                            {{qualification.institution}}</td>
                        <td
                            class="px-6 py-4 whitespace-no-wrap border-b text-custom-primary border-gray-500 text-sm leading-5">
                            {{qualification.qualification_type}}</td>
                        <td
                            class="px-6 py-4 whitespace-no-wrap border-b text-custom-primary border-gray-500 text-sm leading-5">
                            {{qualification.year}}</td>
                        <td class="px-6 py-4 whitespace-no-wrap flex gap-2 text-right border-b border-gray-500 text-sm leading-5">
                            <a href="{{qualification.get_absolute_url}}"
                                class="grid items-center justify-center w-fit py-2 px-3 border-custom-h border text-custom-h  rounded transition duration-300 hover:bg-custom-h hover:text-white focus:outline-none">Update</a>
                            <a href="{% url 'accounts:delete-qualification' qualification.id %}"
                                class="grid items-center justify-center w-fit py-2 px-3 border-red-500 border text-redborder-red-500  rounded transition duration-300 hover:bg-custom-h hover:text-white focus:outline-none">
                                Delete</a>
                        </td>
                        
                    </tr>
                    {% endfor %}

                </tbody>
            </table>

        </div>
    </div>
</div>
{% endblock accountblock %}

accounts/templates/accounts/qualification/update.html
{% extends '_manage.html' %}
{% load static %}

{% block title %}Edit Qualification{% endblock title %}

{% block accountblock %}
<div class='w-full h-full'>
    <div class=" bg-white">
        <div class="space-y-4">
            {% include "includes/errors.html" %}
            <div class="md:px-4">
                
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <h6 class="text-custom-h text-base mt-3 mb-6 font-bold uppercase">
                        Qualifications Information
                    </h6>
                    <div class="flex flex-wrap space-y-3 md:space-y-0">
                        <div class="w-full lg:w-6/12 md:px-4">
                            <div class="relative w-full mb-3">
                                <label for="id_title"
                                    class="block text-custom-h font-semibold text-sm capitalize mb-2"
                                    htmlfor="grid-password">
                                    Title*
                                </label>
                                <input id="id_title" name="title" required maxlength="300" type="text" value="{{form.title.value}}"
                                    class="block p-3 md:text-base w-full text-sm text-custom-h outline-none bg-gray-50 rounded-lg border border-gray-300 focus:ring-custom-primary placeholder:text-gray-400 focus:border-custom-primary ease-linear transition-all duration-150">
                                <span
                                    class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.title.help_text}}</span>

                            </div>
                        </div>
                        <div class="w-full lg:w-6/12 md:px-4">
                            <div class="relative w-full mb-3">
                                <label for="id_year"
                                    class="block text-custom-h font-semibold text-sm capitalize mb-2"
                                    htmlfor="grid-password">
                                    Year range*
                                </label>
                                <input id="id_year" name="year" maxlength="300" type="text" value="{{form.year.value}}"
                                    class="block p-3 md:text-base w-full text-sm text-custom-h outline-none bg-gray-50 rounded-lg border border-gray-300 focus:ring-custom-primary placeholder:text-gray-400 focus:border-custom-primary ease-linear transition-all duration-150">
                                <span
                                    class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.year.help_text}}</span>

                            </div>
                        </div>
                        <div class="w-full lg:w-6/12 md:px-4">
                            <div class="relative w-full mb-3">
                                <label for="id_institution"
                                    class="block text-custom-h font-semibold text-sm capitalize mb-2"
                                    htmlfor="grid-password">
                                    institution*
                                </label>
                                <input id="id_institution" name="institution" maxlength="300" type="text" value="{{form.institution.value}}"
                                    class="block p-3 md:text-base w-full text-sm text-custom-h outline-none bg-gray-50 rounded-lg border border-gray-300 focus:ring-custom-primary placeholder:text-gray-400 focus:border-custom-primary ease-linear transition-all duration-150">

                                <span
                                    class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.institution.help_text}}</span>

                            </div>
                        </div>
                        <div class="w-full lg:w-6/12 md:px-4">
                            <div class="relative w-full mb-3">
                                <label for="id_qualification_type"
                                    class="block text-custom-h font-semibold text-sm capitalize mb-2"
                                    htmlfor="grid-password">
                                    Describe your qualification*
                                </label>
                                {{form.qualification_type}}
                                <span
                                    class="text-[11px] text-custom-tertiary block font-normal lowercase">{{form.qualification_type.help_text}}</span>

                            </div>
                        </div>
                    </div>

                    <div class="text-center mt-6 inline-block h-12 bg-custom-primary w-[150px] rounded-md cursor-pointer">
                        <input type="submit" value="submit"
                            class="text-white w-full h-full cursor-pointer text-sm font-semibold" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock accountblock %}